/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.OperationStatus;

/**
 * Allow specifies supported Operation status, Operation types, and all possible error statuses. This Allow object is used by clients to validate the correctness of a Rosetta Server implementation. It is expected that these clients will error if they receive some response that contains any of the above information that is not specified here.
 */
@ApiModel(description = "Allow specifies supported Operation status, Operation types, and all possible error statuses. This Allow object is used by clients to validate the correctness of a Rosetta Server implementation. It is expected that these clients will error if they receive some response that contains any of the above information that is not specified here.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-01T16:34:45.305718+08:00[Asia/Shanghai]")
public class Allow {
  public static final String SERIALIZED_NAME_OPERATION_STATUSES = "operation_statuses";
  @SerializedName(SERIALIZED_NAME_OPERATION_STATUSES)
  private List<OperationStatus> operationStatuses = new ArrayList<OperationStatus>();

  public static final String SERIALIZED_NAME_OPERATION_TYPES = "operation_types";
  @SerializedName(SERIALIZED_NAME_OPERATION_TYPES)
  private List<String> operationTypes = new ArrayList<String>();

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<Error> errors = new ArrayList<Error>();

  public static final String SERIALIZED_NAME_HISTORICAL_BALANCE_LOOKUP = "historical_balance_lookup";
  @SerializedName(SERIALIZED_NAME_HISTORICAL_BALANCE_LOOKUP)
  private Boolean historicalBalanceLookup;


  public Allow operationStatuses(List<OperationStatus> operationStatuses) {
    
    this.operationStatuses = operationStatuses;
    return this;
  }

  public Allow addOperationStatusesItem(OperationStatus operationStatusesItem) {
    this.operationStatuses.add(operationStatusesItem);
    return this;
  }

   /**
   * All Operation.Status this implementation supports. Any status that is returned during parsing that is not listed here will cause client validation to error.
   * @return operationStatuses
  **/
  @ApiModelProperty(required = true, value = "All Operation.Status this implementation supports. Any status that is returned during parsing that is not listed here will cause client validation to error.")

  public List<OperationStatus> getOperationStatuses() {
    return operationStatuses;
  }


  public void setOperationStatuses(List<OperationStatus> operationStatuses) {
    this.operationStatuses = operationStatuses;
  }


  public Allow operationTypes(List<String> operationTypes) {
    
    this.operationTypes = operationTypes;
    return this;
  }

  public Allow addOperationTypesItem(String operationTypesItem) {
    this.operationTypes.add(operationTypesItem);
    return this;
  }

   /**
   * All Operation.Type this implementation supports. Any type that is returned during parsing that is not listed here will cause client validation to error.
   * @return operationTypes
  **/
  @ApiModelProperty(required = true, value = "All Operation.Type this implementation supports. Any type that is returned during parsing that is not listed here will cause client validation to error.")

  public List<String> getOperationTypes() {
    return operationTypes;
  }


  public void setOperationTypes(List<String> operationTypes) {
    this.operationTypes = operationTypes;
  }


  public Allow errors(List<Error> errors) {
    
    this.errors = errors;
    return this;
  }

  public Allow addErrorsItem(Error errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * All Errors that this implementation could return. Any error that is returned during parsing that is not listed here will cause client validation to error.
   * @return errors
  **/
  @ApiModelProperty(required = true, value = "All Errors that this implementation could return. Any error that is returned during parsing that is not listed here will cause client validation to error.")

  public List<Error> getErrors() {
    return errors;
  }


  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }


  public Allow historicalBalanceLookup(Boolean historicalBalanceLookup) {
    
    this.historicalBalanceLookup = historicalBalanceLookup;
    return this;
  }

   /**
   * Any Rosetta implementation that supports querying the balance of an account at any height in the past should set this to true.
   * @return historicalBalanceLookup
  **/
  @ApiModelProperty(required = true, value = "Any Rosetta implementation that supports querying the balance of an account at any height in the past should set this to true.")

  public Boolean getHistoricalBalanceLookup() {
    return historicalBalanceLookup;
  }


  public void setHistoricalBalanceLookup(Boolean historicalBalanceLookup) {
    this.historicalBalanceLookup = historicalBalanceLookup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Allow allow = (Allow) o;
    return Objects.equals(this.operationStatuses, allow.operationStatuses) &&
        Objects.equals(this.operationTypes, allow.operationTypes) &&
        Objects.equals(this.errors, allow.errors) &&
        Objects.equals(this.historicalBalanceLookup, allow.historicalBalanceLookup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationStatuses, operationTypes, errors, historicalBalanceLookup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Allow {\n");
    sb.append("    operationStatuses: ").append(toIndentedString(operationStatuses)).append("\n");
    sb.append("    operationTypes: ").append(toIndentedString(operationTypes)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    historicalBalanceLookup: ").append(toIndentedString(historicalBalanceLookup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

