/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * CurveType is the type of cryptographic curve associated with a PublicKey.  * secp256k1: SEC compressed - &#x60;33 bytes&#x60; (https://secg.org/sec1-v2.pdf#subsubsection.2.3.3) * edwards25519: &#x60;y (255-bits) || x-sign-bit (1-bit)&#x60; - &#x60;32 bytes&#x60; (https://ed25519.cr.yp.to/ed25519-20110926.pdf)
 */
@JsonAdapter(CurveType.Adapter.class)
public enum CurveType {
  
  SECP256K1("secp256k1"),
  
  EDWARDS25519("edwards25519");

  private String value;

  CurveType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CurveType fromValue(String value) {
    for (CurveType b : CurveType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CurveType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CurveType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CurveType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CurveType.fromValue(value);
    }
  }
}

