/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Amount;
import org.openapitools.client.model.BlockIdentifier;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountBalanceResponse
 */
public class AccountBalanceResponseTest {
    private final AccountBalanceResponse model = new AccountBalanceResponse();

    /**
     * Model tests for AccountBalanceResponse
     */
    @Test
    public void testAccountBalanceResponse() {
        // TODO: test AccountBalanceResponse
    }

    /**
     * Test the property 'blockIdentifier'
     */
    @Test
    public void blockIdentifierTest() {
        // TODO: test blockIdentifier
    }

    /**
     * Test the property 'balances'
     */
    @Test
    public void balancesTest() {
        // TODO: test balances
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
