/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.AccountIdentifier;
import org.openapitools.client.model.NetworkIdentifier;
import org.openapitools.client.model.PartialBlockIdentifier;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountBalanceRequest
 */
public class AccountBalanceRequestTest {
    private final AccountBalanceRequest model = new AccountBalanceRequest();

    /**
     * Model tests for AccountBalanceRequest
     */
    @Test
    public void testAccountBalanceRequest() {
        // TODO: test AccountBalanceRequest
    }

    /**
     * Test the property 'networkIdentifier'
     */
    @Test
    public void networkIdentifierTest() {
        // TODO: test networkIdentifier
    }

    /**
     * Test the property 'accountIdentifier'
     */
    @Test
    public void accountIdentifierTest() {
        // TODO: test accountIdentifier
    }

    /**
     * Test the property 'blockIdentifier'
     */
    @Test
    public void blockIdentifierTest() {
        // TODO: test blockIdentifier
    }

}
