/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.OperationStatus;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Allow
 */
public class AllowTest {
    private final Allow model = new Allow();

    /**
     * Model tests for Allow
     */
    @Test
    public void testAllow() {
        // TODO: test Allow
    }

    /**
     * Test the property 'operationStatuses'
     */
    @Test
    public void operationStatusesTest() {
        // TODO: test operationStatuses
    }

    /**
     * Test the property 'operationTypes'
     */
    @Test
    public void operationTypesTest() {
        // TODO: test operationTypes
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'historicalBalanceLookup'
     */
    @Test
    public void historicalBalanceLookupTest() {
        // TODO: test historicalBalanceLookup
    }

}
