/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.NetworkIdentifier;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionParseRequest
 */
public class ConstructionParseRequestTest {
    private final ConstructionParseRequest model = new ConstructionParseRequest();

    /**
     * Model tests for ConstructionParseRequest
     */
    @Test
    public void testConstructionParseRequest() {
        // TODO: test ConstructionParseRequest
    }

    /**
     * Test the property 'networkIdentifier'
     */
    @Test
    public void networkIdentifierTest() {
        // TODO: test networkIdentifier
    }

    /**
     * Test the property 'signed'
     */
    @Test
    public void signedTest() {
        // TODO: test signed
    }

    /**
     * Test the property 'transaction'
     */
    @Test
    public void transactionTest() {
        // TODO: test transaction
    }

}
