/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.NetworkIdentifier;
import org.openapitools.client.model.Signature;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionCombineRequest
 */
public class ConstructionCombineRequestTest {
    private final ConstructionCombineRequest model = new ConstructionCombineRequest();

    /**
     * Model tests for ConstructionCombineRequest
     */
    @Test
    public void testConstructionCombineRequest() {
        // TODO: test ConstructionCombineRequest
    }

    /**
     * Test the property 'networkIdentifier'
     */
    @Test
    public void networkIdentifierTest() {
        // TODO: test networkIdentifier
    }

    /**
     * Test the property 'unsignedTransaction'
     */
    @Test
    public void unsignedTransactionTest() {
        // TODO: test unsignedTransaction
    }

    /**
     * Test the property 'signatures'
     */
    @Test
    public void signaturesTest() {
        // TODO: test signatures
    }

}
