/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.SigningPayload;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionPayloadsResponse
 */
public class ConstructionPayloadsResponseTest {
    private final ConstructionPayloadsResponse model = new ConstructionPayloadsResponse();

    /**
     * Model tests for ConstructionPayloadsResponse
     */
    @Test
    public void testConstructionPayloadsResponse() {
        // TODO: test ConstructionPayloadsResponse
    }

    /**
     * Test the property 'unsignedTransaction'
     */
    @Test
    public void unsignedTransactionTest() {
        // TODO: test unsignedTransaction
    }

    /**
     * Test the property 'payloads'
     */
    @Test
    public void payloadsTest() {
        // TODO: test payloads
    }

}
