/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Operation;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConstructionParseResponse
 */
public class ConstructionParseResponseTest {
    private final ConstructionParseResponse model = new ConstructionParseResponse();

    /**
     * Model tests for ConstructionParseResponse
     */
    @Test
    public void testConstructionParseResponse() {
        // TODO: test ConstructionParseResponse
    }

    /**
     * Test the property 'operations'
     */
    @Test
    public void operationsTest() {
        // TODO: test operations
    }

    /**
     * Test the property 'signers'
     */
    @Test
    public void signersTest() {
        // TODO: test signers
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
