/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TransactionIdentifier;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MempoolResponse
 */
public class MempoolResponseTest {
    private final MempoolResponse model = new MempoolResponse();

    /**
     * Model tests for MempoolResponse
     */
    @Test
    public void testMempoolResponse() {
        // TODO: test MempoolResponse
    }

    /**
     * Test the property 'transactionIdentifiers'
     */
    @Test
    public void transactionIdentifiersTest() {
        // TODO: test transactionIdentifiers
    }

}
