/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BlockIdentifier;
import org.openapitools.client.model.Peer;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NetworkStatusResponse
 */
public class NetworkStatusResponseTest {
    private final NetworkStatusResponse model = new NetworkStatusResponse();

    /**
     * Model tests for NetworkStatusResponse
     */
    @Test
    public void testNetworkStatusResponse() {
        // TODO: test NetworkStatusResponse
    }

    /**
     * Test the property 'currentBlockIdentifier'
     */
    @Test
    public void currentBlockIdentifierTest() {
        // TODO: test currentBlockIdentifier
    }

    /**
     * Test the property 'currentBlockTimestamp'
     */
    @Test
    public void currentBlockTimestampTest() {
        // TODO: test currentBlockTimestamp
    }

    /**
     * Test the property 'genesisBlockIdentifier'
     */
    @Test
    public void genesisBlockIdentifierTest() {
        // TODO: test genesisBlockIdentifier
    }

    /**
     * Test the property 'oldestBlockIdentifier'
     */
    @Test
    public void oldestBlockIdentifierTest() {
        // TODO: test oldestBlockIdentifier
    }

    /**
     * Test the property 'peers'
     */
    @Test
    public void peersTest() {
        // TODO: test peers
    }

}
