/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.SubNetworkIdentifier;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NetworkIdentifier
 */
public class NetworkIdentifierTest {
    private final NetworkIdentifier model = new NetworkIdentifier();

    /**
     * Model tests for NetworkIdentifier
     */
    @Test
    public void testNetworkIdentifier() {
        // TODO: test NetworkIdentifier
    }

    /**
     * Test the property 'blockchain'
     */
    @Test
    public void blockchainTest() {
        // TODO: test blockchain
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'subNetworkIdentifier'
     */
    @Test
    public void subNetworkIdentifierTest() {
        // TODO: test subNetworkIdentifier
    }

}
