/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.NetworkIdentifier;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NetworkListResponse
 */
public class NetworkListResponseTest {
    private final NetworkListResponse model = new NetworkListResponse();

    /**
     * Model tests for NetworkListResponse
     */
    @Test
    public void testNetworkListResponse() {
        // TODO: test NetworkListResponse
    }

    /**
     * Test the property 'networkIdentifiers'
     */
    @Test
    public void networkIdentifiersTest() {
        // TODO: test networkIdentifiers
    }

}
