/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CurveType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PublicKey
 */
public class PublicKeyTest {
    private final PublicKey model = new PublicKey();

    /**
     * Model tests for PublicKey
     */
    @Test
    public void testPublicKey() {
        // TODO: test PublicKey
    }

    /**
     * Test the property 'hexBytes'
     */
    @Test
    public void hexBytesTest() {
        // TODO: test hexBytes
    }

    /**
     * Test the property 'curveType'
     */
    @Test
    public void curveTypeTest() {
        // TODO: test curveType
    }

}
