/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.SignatureType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SigningPayload
 */
public class SigningPayloadTest {
    private final SigningPayload model = new SigningPayload();

    /**
     * Model tests for SigningPayload
     */
    @Test
    public void testSigningPayload() {
        // TODO: test SigningPayload
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'hexBytes'
     */
    @Test
    public void hexBytesTest() {
        // TODO: test hexBytes
    }

    /**
     * Test the property 'signatureType'
     */
    @Test
    public void signatureTypeTest() {
        // TODO: test signatureType
    }

}
