/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Version
 */
public class VersionTest {
    private final Version model = new Version();

    /**
     * Model tests for Version
     */
    @Test
    public void testVersion() {
        // TODO: test Version
    }

    /**
     * Test the property 'rosettaVersion'
     */
    @Test
    public void rosettaVersionTest() {
        // TODO: test rosettaVersion
    }

    /**
     * Test the property 'nodeVersion'
     */
    @Test
    public void nodeVersionTest() {
        // TODO: test nodeVersion
    }

    /**
     * Test the property 'middlewareVersion'
     */
    @Test
    public void middlewareVersionTest() {
        // TODO: test middlewareVersion
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
