/*
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.Error;
import com.prokarma.pkmst.model.MempoolResponse;
import com.prokarma.pkmst.model.MempoolTransactionRequest;
import com.prokarma.pkmst.model.MempoolTransactionResponse;
import com.prokarma.pkmst.model.NetworkRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for MempoolApi
 */
@Ignore
public class MempoolApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final MempoolApi api = new MempoolApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Get All Mempool Transactions
     *
     * Get all Transaction Identifiers in the mempool
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void mempoolTest() throws Exception {
        NetworkRequest networkRequest = null;
    ResponseEntity<MempoolResponse> response = api.mempool(networkRequest , accept);

        // TODO: test validations
    }
    
    /**
     * Get a Mempool Transaction
     *
     * Get a transaction in the mempool by its Transaction Identifier. This is a separate request than fetching a block transaction (/block/transaction) because some blockchain nodes need to know that a transaction query is for something in the mempool instead of a transaction in a block. Transactions may not be fully parsable until they are in a block (ex: may not be possible to determine the fee to pay before a transaction is executed). On this endpoint, it is ok that returned transactions are only estimates of what may actually be included in a block.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void mempoolTransactionTest() throws Exception {
        MempoolTransactionRequest mempoolTransactionRequest = null;
    ResponseEntity<MempoolTransactionResponse> response = api.mempoolTransaction(mempoolTransactionRequest , accept);

        // TODO: test validations
    }
    
}
